[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
#####
addopts =
    -v
    --tb=short
    --screenshot=only-on-failure
    --output=output/screenshots
    --video=retain-on-failure

markers =
    smoke: быстрые базовые проверки
    regression: полный регрессионный набор
    ui: тесты интерфейса
    performance: тесты производительности
    cross_browser: кросс-браузерные тесты
    security: тесты безопасности
